Module15 task3
MattStefanski/JavaSpring pull request #3
Opened 2018-06-19 20:49 UTC by MattStefanski

2018-06-20 06:43 UTC, MARudnicki requested changes

2018-06-20 06:43 UTC, MARudnicki commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +import antlr.TokenStreamException;
co to za import ?

2018-06-25 19:51 UTC, MattStefanski commented
Testy działając jednak w postmanie na komendę http://localhost:8080/v1/task/getTask?taskId=1 dostaję notfound exception

2018-06-26 06:07 UTC, MARudnicki requested changes

2018-06-26 06:07 UTC, MARudnicki commented on src/main/java/com/crud/tasks/controller/TaskController.java
>      }
To powinno wygladac tak
```
    @RequestMapping(method = RequestMethod.GET, value = "getTask/{taskId}")
    public Task getTask(@PathVariable Long taskId) throws TaskNotFoundException {

        System.out.println("Task id : "+taskId);

        return taskMapper.mapToTaskDto(service.getTask(taskId).orElseThrow(TaskNotFoundException::new));
    }

```

2018-06-26 06:07 UTC, MARudnicki commented on src/main/java/com/crud/tasks/controller/TaskController.java
>      }
Zwroc uwage na @PathVariable
Odwolujesz sie tak
`http://localhost:8080/v1/task/getTask/1`

2018-06-27 06:27 UTC, MARudnicki requested changes

2018-06-27 06:27 UTC, MARudnicki commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +        service.deleteTask(service.getTask(taskId).orElseThrow(TaskNotFoundException::new));
to nie powinno byc request body, tylko requestParam

2018-06-27 06:27 UTC, MARudnicki commented on src/main/java/com/crud/tasks/controller/TaskController.java
> +        service.deleteTask(service.getTask(taskId).orElseThrow(TaskNotFoundException::new));
* podejrzyj w branchu ktory stworzylismy wczoraj

2018-06-28 22:02 UTC, merged